### PR TITLE
Add hacktoberfest command with test

### PR DESCRIPTION
**Pull request by Colin-Suckow**
Does what it says on the tin. We will add more information as it becomes available.

### CODE REVIEW

**Review by ctsstc — APPROVED** [review]
LGTM 🚀

**Comment by ctsstc** [comment]
I'll push this up to staging so it can be tested.

**Comment by ctsstc** [comment]
For a future update you may want to pull a list of projects from an environment variable so that it does not require a code change + redeploy if you plan on modifying a list often.

**Comment by Colin-Suckow** [comment]
> For a future update you may want to pull a list of projects from an environment variable so that it does not require a code change + redeploy if you plan on modifying a list often.

Good point. I'll do that on the next update.

**Pull request merged**
